# Site wide configuration

title: Les Geeks du Dimanche
locale: fr_FR
description: Parce que l'informatique c'est serieux \#Brioche \#ClashEnBash"
logo: lesbricodeurs.png
url: //127.0.0.1:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

comments: true

# Site owner
owner:
  name: Les Geeks du Dimanche
  avatar: brioche.jpg
  email: xavier+lavayssiere+LesGeeksDuDimanche@gmail.com
  disqus-shortname: LesGeeksDuDimanche
  twitter: Lesbricodeurs
  facebook: pages/Les-Bricodeurs/130913190581576
  github: LesGeeksDuDimanche
  stackexchange:
  linkedin:
  instagram: 
  flickr:
  tumblr: 
  pinterest:
  weibo:
  google:
    plus: 
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
